### ISSUE TITLE
Using Actions in Multiple Locations

### ISSUE THREAD

**Issue by DevDwarf** [sigmadigitalza/duxedo#1]
I am currently unclear as to how this can be used on multiple files, i.e.
having a logout action that can be imported on a logout component and a routing listener component for instance.

Will have to pull it down and test on a demo project.

**Comment by Pushplaybang** [comment]
Hey so this can be done using aliases, ie:

```js
// in a component
import { actions as counter } from '../store/definitions/counter';

// in a reducer
import { reducer as audioPlayer } from './definitions/audioPlayer';
```

**Comment by Pushplaybang** [comment]
https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

you can also alias on export if you prefer.

**Comment by Pushplaybang** [comment]
@DevDwarf  - can we close?
