### ISSUE TITLE
Basic Sructure

### ISSUE THREAD

**Issue by DevDwarf** [sigmadigitalza/duxedo#2]
How would the structure look from a dev prespective now, currently you would have something like:

```
store
   |___ Actions
   |___ Reducers
   |___ Constants
```

Would only Actions be applicable now? Think Constants can also stay, just thinking about this in a React way of setting this up.

**Comment by Pushplaybang** [comment]
How I've approached this is:

```
store
   |___ definitions
               |___ audioPlayer.js
               |___ queue.js
               |___ auth.js
   |___ index.js
```

also, note you should only capitalise files and folders for components.
